'use strict';
const dialog=document.querySelector('#preview-dialog');
const title=document.querySelector('#dialog-title');
const body=document.querySelector('#dialog-content');
let lastFocus=null;
function openDialog(heading,paragraphs,note){lastFocus=document.activeElement;title.textContent=heading;body.replaceChildren();if(note){const p=document.createElement('p');p.className='dialog-note';p.textContent=note;body.append(p);}paragraphs.forEach(text=>{const p=document.createElement('p');p.textContent=text;body.append(p);});dialog.showModal();dialog.scrollTop=0;document.querySelector('#dialog-close').focus();}
document.querySelector('#dialog-close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('close',()=>lastFocus?.focus());
dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}});
let videos=[];
document.addEventListener('click',event=>{const video=event.target.closest('[data-video]');if(video){const v=videos[Number(video.dataset.video)];if(v)openDialog(v.title,v.paragraphs,'Recording pending. This is the exact script for this video.');else openDialog('Video script unavailable',['Please refresh the page and try again.']);return;}const calendar=event.target.closest('[data-calendar]');if(calendar)openDialog('Add to '+calendar.dataset.calendar,['Tuesday, September 22, 2026. 10:00–10:30 a.m. America/Chicago.','On the finished page, this button will add the actual booked appointment to your calendar.'],'Sample booking only. No calendar event has been created.');const action=event.target.closest('[data-action]');if(action)openDialog(action.dataset.action==='join'?'Your meeting details':'Choose another time',['This design uses a sample appointment to show the confirmation experience. The finished page will use the meeting and rescheduling links from the actual booking.'],'Design preview. No live appointment is connected.');});
const featured=[3,9,7,4,5,10];
const coverTitles={1:'A qualified,\nheld appointment.',2:'Where the\nconversation starts.',6:'They know\nwho you are.',8:'When the fit\nisn’t right.',11:'Appointments\nand outcomes.',12:'The agreement.\nIn plain terms.',13:'Come ready\nto talk.',14:'A change\nof plans.',3:'Before it reaches\nyour calendar.',9:'The terms.\nClear upfront.',7:'What if they\ndon’t show?',4:'The right\nasset range.',5:'Your states.\nYour clients.',10:'A pace that\nfits your team.'};
let expanded=false;
function renderVideos(){const order=expanded?[...featured,...videos.map((_,i)=>i).filter(i=>i>0&&!featured.includes(i))]:featured;const grid=document.querySelector('#video-grid');grid.replaceChildren();order.forEach(i=>{const v=videos[i];const button=document.createElement('button');button.className='video-card';button.dataset.video=String(i);const cover=document.createElement('div');cover.className='video-cover';const top=document.createElement('div');top.className='cover-top';const brand=document.createElement('span');brand.textContent='TRP / BEFORE WE MEET';const number=document.createElement('span');number.textContent=String(i+1).padStart(2,'0');top.append(brand,number);const ctitle=document.createElement('div');ctitle.className='cover-title';ctitle.textContent=coverTitles[i]||v.title;const bottom=document.createElement('div');bottom.className='cover-bottom';const runtime=document.createElement('span');runtime.textContent=v.runtime;const play=document.createElement('span');play.className='mini-play';play.textContent='▶';play.setAttribute('aria-hidden','true');bottom.append(runtime,play);cover.append(top,ctitle,bottom);const h=document.createElement('h3');h.textContent=v.title;const p=document.createElement('p');p.textContent='Read script · Recording pending';button.append(cover,h,p);grid.append(button);});}
document.querySelector('#library-toggle').addEventListener('click',event=>{expanded=!expanded;renderVideos();event.currentTarget.setAttribute('aria-expanded',String(expanded));event.currentTarget.textContent=expanded?'Show the essentials ↑':'Explore all 14 topics ↓';});
fetch('videos.json').then(r=>{if(!r.ok)throw Error('Video content unavailable');return r.json();}).then(data=>{videos=data;renderVideos();const faq=document.querySelector('#faq-list');videos.slice(1).forEach(v=>{const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent=v.title;const answer=document.createElement('div');answer.className='faq-answer';v.paragraphs.slice(v.paragraphs[0]===v.title?1:0).forEach(text=>{const p=document.createElement('p');p.textContent=text;answer.append(p);});details.append(summary,answer);faq.append(details);});}).catch(()=>{document.querySelector('#video-grid').textContent='The scripts could not load. Please refresh to try again.';document.querySelector('#faq-list').textContent='The answers could not load. Please refresh to try again.';document.querySelector('#library-toggle').hidden=true;});
const slideNames=['Company overview','Company overview','Challenges in retirement lead gen','Value proposition','The appointment engine','How it works','Who is on the other side','Team','Thank you'];let slide=0;
function showSlide(delta){slide=(slide+delta+9)%9;const img=document.querySelector('#deck-image');img.src='../confirmed-booking/deck/slide-'+(slide+1)+'.jpg';img.alt='Slide '+(slide+1)+' of 9: '+slideNames[slide];const caption=document.querySelector('#deck-label');caption.replaceChildren(document.createTextNode(String(slide+1).padStart(2,'0')+' / 09 '));const text=document.createElement('span');text.textContent=slideNames[slide];caption.append(text);}
document.querySelector('#deck-prev').addEventListener('click',()=>showSlide(-1));document.querySelector('#deck-next').addEventListener('click',()=>showSlide(1));document.querySelector('.deck-viewer').addEventListener('keydown',event=>{if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();showSlide(event.key==='ArrowLeft'?-1:1);}});
